<a href="https://colab.research.google.com/github/Vasudevan0057/DHV/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np


import numpy as np
array_1d = np.array([1, 2, 3, 4, 5])
print(array_1d.shape)
print(array_1d.size)
print(array_1d.ndim)
print(len(array_1d))
array_2d = np.array([[1, 2, 3],
                     [4, 5, 6]])
print(array_2d.shape)
print(array_2d.size)
print(array_2d.ndim)
print(len(array_2d))
array_3d = np.array([[[1, 2, 3],
                      [4, 5, 6]],

                     [[7, 8, 9],
                      [10, 11, 12]]])
print(array_3d.shape)
print(array_3d.size)
print(array_3d.ndim)
print(len(array_3d))

(5,)
5
1
5
(2, 3)
6
2
2
(2, 2, 3)
12
3
2


In [2]:
a_example = np.arange(1, 10, 2)
print(a_example)
randint_example = np.random.randint(1, 100, size=(3, 3))
print(randint_example)
rand_example = np.random.rand(2, 3)
print(rand_example)
lspace_example = np.linspace(1, 10, num=5)
print(lspace_example)
ones_example = np.ones((2, 3))
print(ones_example)
zeros_example = np.zeros((3, 2))
print(zeros_example)
diag_example = np.diag([1, 2, 3])
print(diag_example)


[1 3 5 7 9]
[[75 85 10]
 [14 48 17]
 [ 6  7 25]]
[[0.40739579 0.15694331 0.49800529]
 [0.922887   0.93410586 0.96018792]]
[ 1.    3.25  5.5   7.75 10.  ]
[[1. 1. 1.]
 [1. 1. 1.]]
[[0. 0.]
 [0. 0.]
 [0. 0.]]
[[1 0 0]
 [0 2 0]
 [0 0 3]]


In [3]:
marks= np.random.randint(0, 101, size=10)
print(marks)


[61 34 22 37 83 10 28 67 54 97]


In [4]:
f_marks= marks[marks < 30]
print(f_marks)

[22 10 28]


In [5]:
print(f_marks)
pmarks=marks[marks>=30]
print(pmarks)
rows = 3
cols = 4
random_2d_array = np.random.rand(rows, cols)
print(random_2d_array)

[22 10 28]
[61 34 37 83 67 54 97]
[[0.29227471 0.05416431 0.62206235 0.13698369]
 [0.426141   0.75426902 0.86264226 0.87155649]
 [0.81977897 0.29258302 0.51024774 0.2535092 ]]
